export const tags: any = [
  {
    id: "314",
    name: "Ακμή",
    slug: "acne",
    children: [
      { id: "315", name: "Φαγεσωρική Ακμή", slug: "fagesoriki", children: null },
      {
        id: "316",
        name: "Φλεγμονική Ακμή",
        slug: "flegmoniki",
        children: null,
      },
    ],
  },
  {
    id: "317",
    name: "Λιπαρότητα/ Διεσταλμένοι Πόροι",
    slug: "liparotita",
    children: null,
  },
  {
    id: "318",
    name: "Δυσχρωμίες/ Πανάδες/ Μέλασμα",
    slug: "disxromies",
    children: null,
  },
  {
    id: "319",
    name: "Ρυτίδες",
    slug: "ritides",
    children: [
      {
        id: "320",
        name: "Αντιγήρανση/Πρόληψη",
        slug: "antigiransi",
        children: null,
      },
      {
        id: "321",
        name: "Λαιμός/ Ντεκολτέ",
        slug: "laimos",
        children: null,
      },
      {
        id: "322",
        name: "Σύσφιξη",
        slug: "sisfixi",
        children: null,
      },
    ],
  },
  {
    id: "323",
    name: "Θαμπή Όψη",
    slug: "thabiopsi",
    children: null,
  },
  {
    id: "324",
    name: "Μάτια",
    slug: "matia",
    children: [
      {
        id: "325",
        name: "Σακούλες",
        slug: "sakoules",
        children: null,
      },
      {
        id: "326",
        name: "Ρυτίδες",
        slug: "ritidesmatiwn",
        children: null,
      },
      { id: "327",  name: "Μαύροι Κύκλοι", slug: "mavroikikloi", children: null },
    ],
  },
  {
    id: "328",
    name: "Ξηρότητα",
    slug: "xirotita",
    children: null,
  },
  {
    id: "329",
    name: "Ευαίσθητο Δέρμα/ Ροδόχρους",
    slug: "rodoxrous",
    children: null,
  },
  {
    id: "330",
    name: "Αποκατάσταση Δέρματος/ Ανάπλαση",
    slug: "anaplasi",
    children: null,
  },
];